HasangerGames/suroi

- README.md
- client/src/assets/scss/pages/client/game.scss
- client/src/scripts/game.ts
- client/src/scripts/packets/receiving/joinedPacket.ts
- client/src/scripts/scenes/gameScene.ts
- package.json
- pnpm-lock.yaml
start a local dev with 1 command instead of 4 ( && doesn't work in my terminal of choice ), it also eliminates the need for two terminals.
> chore(package): refactor dev scripts for simpler dev setup

- client/src/scripts/game.ts
the game starts shaking if you press the start button too quickly.
> fix: prevent creating multiple Phaser scenes when starting a game.

- client/src/assets/scss/pages/client.scss
- client/src/pages/index.html
- client/src/scripts/game.ts
- client/src/scripts/packets/receiving/updatePacket.ts
- client/src/scripts/scenes/gameScene.ts
- client/src/scripts/scenes/menuScene.ts
- client/src/scripts/ui.ts
"quit game" button doesn't do anything yet, may add more stuff later.
> feat: add game settings

- client/src/assets/img/game/particles/heal_particle.svg
Code in a heal particle I added an
added an image
Look I can't test this im not smart enough to do the shenanigans to run this and test, its just an image I wanted to add to say that I contributed, its not gonna be active, its just an image you guys could use
> created a heal particle

- client/src/assets/scss/pages/client/game.scss
- client/src/pages/index.html
- client/src/scripts/game.ts
- client/src/scripts/packets/receiving/killFeedPacket.ts
- common/src/constants.ts
- server/src/game.ts
- server/src/objects/player.ts
- server/src/packets/sending/killFeedPacket.ts
doesn't display when the player kills himself with the barrel yet.
also, the "killed with fists" message is hardcoded for now.
> feat: implement kill feed

- client/src/scripts/game.ts
- client/src/scripts/main.ts
- client/src/scripts/objects/player.ts
- client/src/scripts/scenes/minimapScene.ts
- client/src/scripts/ui.ts
- client/src/scripts/utils/inputManager.ts
- client/src/scripts/utils/localStorageHandler.ts
- common/src/constants.ts
- common/src/utils/math.ts
- common/src/utils/objectType.ts
- common/src/utils/random.ts
- server/src/config.ts
- server/src/game.ts
- server/src/inventory/inventory.ts
- server/src/map.ts
I decided to pop into the codebase to see what was up, only to remember I was gonna be gone for the weekend, so here's a bite-sized PR
* **addition**: Added a `Config` type for the, well, server-side config
* **docs**: Moved some documentation comments to more suitable places
* **style**: Who forgot to run their linter before committing bruh
* **refactor**: Improved the code for spawning in players
* **enhancement**: Improved the code for porting configs
And a bunch of other grammar fixes, nitpicking, things, stuff and eipi-brand fluff™
I didn't test it, realized I should, fixed all the stuff that broke, then forgot to change the stuff I changed to test, and changed that.
> more minor stuff

- common/src/utils/vector.ts
I added code comments to just one page (vector.ts). Probably over commented, but better than bare code. 
* **docs**: Documentation only changes.
* **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc).
* **refactor**: A code change that neither fixes a bug nor adds a feature.
> increase readability

- common/src/definitions/obstacles.ts
Fixed the bug in which the gold rock spawned on the minimap/
Went to the spot where it was spawned on the map and it wasn't there.
> Gold rock no longer appears on Minimap

- common/src/definitions/melees.ts
Make bat more realistic, just changing its animation
* **refactor**: A code change that neither fixes a bug nor adds a feature.
Pickup bat and hit it.
> Enhance bat animation

- client/src/pages/changelog.html
- client/src/pages/index.html
- client/src/pages/rules.html
- client/src/rules.ts
- client/src/scripts/rules/ruleGenerator.ts
- client/src/scripts/rules/rulePosts.ts
- client/src/scripts/rules/ruleWidget.ts
- client/src/scss/pages/rules.scss
- client/src/scss/palette.scss
- client/src/scss/utils/buttons.scss
- client/webpack/webpack.common.ts
I updated the changelog, and made a new button that opens rules and a tutorial
* **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc).
* **refactor**: A code change that neither fixes a bug nor adds a feature.
um i ran it ig
> Rules, Tutorial, Updated Changelog

- client/public/audio/credits.txt
- client/public/img/credits.txt
Reformatted + updated audio credits
Split the credits into sections for guns and obstacles, and more organization.
Update to credits.txt
Does not affect code.
> Updated artist and sound credits

- client/public/img/credits.txt
Added several missing credits
Uhh.. refactor? idk
Does not affect code.
> Added missing credits for some art

- client/src/scss/pages/dialog.scss
not tested, committed directly from GitHub at 6 AM : )
just visited the website after a while and the progress you guys made is seriously impressive, keep up the good work.
> fix: skin not displaying properly

- client/src/scripts/utils/inputManager.ts
Finally got around to fixing an oversight
* **fix**: Modifiers no longer prevent key releases from being honoured.
I pressed buttons
> fix inputs but not on the main branch this time

- client/src/pages/index.html
- client/src/scripts/objects/deathMarker.ts
- client/src/scripts/packets/receiving/gameOverPacket.ts
- client/src/scripts/packets/receiving/killFeedPacket.ts
- client/src/scripts/packets/receiving/killPacket.ts
- client/src/scripts/ui.ts
- client/src/scripts/utils/constants.ts
- client/src/scripts/utils/localStorageHandler.ts
Added an option to anonymize player names in game.
Joined the game with different tabhs and the join log was Player, shot/killed other players and there name was not shown, players killed themselves and were not shown
> Added in Anonymous Players

- server/src/server.ts
I changed the server side username modification to make the username `Player` if the username is empty after stripping ASCII chars.
> Changed server side username modification

- client/src/pages/index.html
- client/src/scripts/objects/player.ts
- client/src/scripts/ui.ts
- client/src/scripts/utils/localStorageHandler.ts
Added X and Y positions to the debug HUD
* 
On my local machine with Google Chrome web browser.
> Coordinates on HUD

- client/src/pages/index.html
- client/src/scripts/objects/player.ts
- client/src/scripts/ui.ts
Fixed the issue when the player could shoot when on the in-game pause menu. 
* **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc).
On local machine using Google Chrome.
> Fixed Shooting in Pause Menu

- client/src/scss/utils/inputs.scss
iOS checkbox bug fix
Tested on iOS 17.1 iPhone 13 Google Chrome
Tested on Windows 11 Ryzen 7 5800x3D & RX 6750 XT & 32GB 3600Mhz Memory (it's only here for flex purposes)
Tested on Android 12
> iOS checkbox bug fix

- client/src/pages/index.html
- client/src/scripts/packets/receiving/gameOverPacket.ts
- client/src/scripts/ui.ts
- client/src/scripts/utils/localStorageHandler.ts
- client/src/scss/pages/client/game.scss
- common/src/definitions/guns.ts
- server/src/config.ts
- server/src/objects/player.ts
Chicken dinner now doesn't clip out of screen on mobile devices
Ammo Splits up on player death
Local machine on Google Chrome
> Chicken Dinner back on screen!!! :trollface:  + Split Ammo

- server/src/server.ts
Fixed loophole when entering ascii chars in between slur ascii stripped after bad words check causing slur to pass.
> Fixing slurs in username loophole

- client/src/pages/index.html
Line was supposed to be removed when custom cursors were first added but I guess I forgot.
> Removed redundant line

- common/src/definitions/guns.ts
- server/src/inventory/gunItem.ts
Mainly for the balancing of shotguns, randomizes bullet position
Tested with `pnpm dev`
> feat: Add gun jitter

- client/src/scripts/packets/receiving/mapPacket.ts
- client/src/scripts/rendering/map.ts
- common/src/utils/mapUtils.ts
- common/src/utils/math.ts
- common/src/utils/random.ts
- server/src/inventory/gunItem.ts
- server/src/map.ts
lots of stuff I didn't do, please clean up haha
have fun Leia
> Fix river generation

- client/src/pages/index.html
- client/src/scss/pages/dialog.scss
- client/src/scss/utils/tabs.scss
Grid emoji selector, moved settings button, scaffolding for settings import/export
> feat: :zap: Small UI enhancements

- client/src/pages/index.html
> Reference for full restart in settings

- client/src/pages/index.html
- client/src/scripts/game.ts
- client/src/scripts/packets/receiving/updatePacket.ts
- client/src/scss/pages/client/game.scss
- server/src/packets/sending/updatePacket.ts
Added option to spectate kill leader. Tested.
> Added option to spectate kill leader

- common/src/definitions/guns.ts
- common/src/packets/updatePacket.ts
- server/src/config.ts
- server/src/game.ts
- server/src/inventory/gunItem.ts
- server/src/inventory/inventoryItem.ts
- server/src/objects/loot.ts
This spawn mode is like random but with a minimum distance between players
> feat: :sparkles: Poisson Disc spawn mode

- client/src/scripts/config.ts
- client/src/scripts/rendering/gas.ts
- client/src/scripts/utils/constants.ts
- common/src/definitions/buildings.ts
- common/src/definitions/bullets.ts
- common/src/definitions/explosions.ts
- common/src/definitions/guns.ts
- common/src/definitions/healingItems.ts
- common/src/definitions/melees.ts
- common/src/definitions/modes.ts
- common/src/definitions/obstacles.ts
- common/src/utils/hitbox.ts
- server/src/config.ts
- server/src/data/lootTables.ts
- server/src/data/maps.ts
- server/src/map.ts
- server/src/objects/loot.ts
- server/src/server.ts
- server/src/utils/grid.ts
- server/src/utils/idAllocator.ts
- server/src/utils/misc.ts
- server/src/validateDefinitions.ts
this is an extremely important pr that will change the course of history (source: trust me)
* **enhancement**: updated the dv
* **enhancement**: marked more stuff as `readonly`
* **enhancement**: privatized stuff (insert political joke here)
* **refactor**: renamed `common::BuildingDecal#rotation` to `orientation` for accuracy
* **enhancement**: please use `ReferenceTo` for fields that expect `idString`s
* **fix**: matched the revitalizer's tracer length to that of the m37
* **style**: the usual breaking onto lines & inlining
* **enhancement**: made all the `Hitbox` subclass error messages more informative
> enhance: dv improvements

- server/src/data/lootTables.ts
- server/src/map.ts
- server/src/objects/obstacle.ts
- server/src/utils/misc.ts
- server/src/validateDefinitions.ts
- fixed the dv (lol)
- removed the no-item item (grrr)
- renamed a method to respect camel case
- if you intend for a `string` to represent an `idString`, please use the appropriate `ReferenceTo` type, thanks :3
> dv fix, other funnies

- client/src/scripts/ui.ts
> feat: add item dropping for mobile

- client/src/scripts/ui.ts
- client/src/scss/pages/client/game.scss
Small UI Fixes / Improvements:
- Removed extra space above kill feed
- Made space between edge of screen and ammos/heals same as space between gun slots (5px)
- Added throwable cycling by pressing the inventory slot
> Small UI Fixes / Improvements

- client/index.html
- client/src/scripts/ui.ts
- client/src/scss/pages/client/game.scss
Features added as directed by devs, client changes only
> Added spectator menu controls

- client/src/scripts/utils/console/commands.ts
- client/src/scripts/utils/inputManager.ts
client changes only, bugfix only
> Continuous fire bug hotfix + typo corrections

- client/src/scripts/objects/loot.ts
- common/src/constants.ts
- server/src/game.ts
- server/src/objects/loot.ts
https://github.com/HasangerGames/suroi/assets/101949387/e540dd9d-e804-4f6e-a3ef-645c76eb62e1
https://github.com/HasangerGames/suroi/assets/101949387/9c1ed57f-e497-4ea4-9ce0-9da386f644f7
I made this change to make the game more enjoyable to play
because that was the thing that impressed me most about the original surviv.io
see more on: ```suroi.io discord server/suggestions forum/Better Die Animations
> refactor .: better loot animation

- client/src/scripts/ui.ts
he can get on the list.
He made video and live, got a lot of views.
and has the tag youtuber with badge
> Add Gamerio Into Youtubers List

- common/src/utils/objectDefinitions.ts
- common/src/utils/terrain.ts
- server/src/data/maps.ts
- server/src/map.ts
Now its faster and way more evenly distributed
also removed river bank spawn mode because it was broken and unused
Also hiiii random persons seeing me do a commit on suroi and having no idea what happened
i just wanted to fix shit code i made a year ago, I'm not coming back as an actual dev this is just a random contribution because i was bored :3
> fix: fix obstacle generation on rivers

- client/src/scripts/game.ts
- client/src/scripts/managers/mapManager.ts
- client/src/scripts/managers/uiManager.ts
refactored function to their corresponding manager instead of clogging endgame() function
> refactor: cleaned endgame() function
